"""add memory tables"""

revision = 'c69a9ee239fd'
down_revision = '20260523_0016'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_suites_active'), table_name='evaluation_suites')
    op.drop_index(op.f('ix_evaluation_suites_mode'), table_name='evaluation_suites')
    op.drop_index(op.f('ix_evaluation_suites_name'), table_name='evaluation_suites')
    op.drop_table('evaluation_suites')
    op.drop_index(op.f('ix_evaluation_case_results_case_id'), table_name='evaluation_case_results')
    op.drop_index(op.f('ix_evaluation_case_results_evaluation_run_id'), table_name='evaluation_case_results')
    op.drop_index(op.f('ix_evaluation_case_results_status'), table_name='evaluation_case_results')
    op.drop_index(op.f('ix_evaluation_case_results_target_type'), table_name='evaluation_case_results')
    op.drop_table('evaluation_case_results')
    op.drop_index(op.f('ix_evaluation_runs_mode'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_name'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_run_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_started_at'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_status'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_suite_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_evaluation_cases_active'), table_name='evaluation_cases')
    op.drop_index(op.f('ix_evaluation_cases_mode'), table_name='evaluation_cases')
    op.drop_index(op.f('ix_evaluation_cases_name'), table_name='evaluation_cases')
    op.drop_index(op.f('ix_evaluation_cases_suite_id'), table_name='evaluation_cases')
    op.drop_index(op.f('ix_evaluation_cases_target_type'), table_name='evaluation_cases')
    op.drop_table('evaluation_cases')
    op.create_index(op.f('ix_agent_runs_model_name'), 'agent_runs', ['model_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_provider'), 'agent_runs', ['provider'], unique=False)
    op.create_foreign_key(None, 'run_screenshots', 'agent_runs', ['agent_run_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.drop_constraint(None, 'run_screenshots', type_='foreignkey')
    op.drop_index(op.f('ix_agent_runs_provider'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_model_name'), table_name='agent_runs')
    op.create_table('evaluation_cases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('suite_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=32), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('input_json', sqlite.JSON(), nullable=False),
    sa.Column('assertions_json', sqlite.JSON(), nullable=False),
    sa.Column('metadata_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['evaluation_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_cases_target_type'), 'evaluation_cases', ['target_type'], unique=False)
    op.create_index(op.f('ix_evaluation_cases_suite_id'), 'evaluation_cases', ['suite_id'], unique=False)
    op.create_index(op.f('ix_evaluation_cases_name'), 'evaluation_cases', ['name'], unique=False)
    op.create_index(op.f('ix_evaluation_cases_mode'), 'evaluation_cases', ['mode'], unique=False)
    op.create_index(op.f('ix_evaluation_cases_active'), 'evaluation_cases', ['active'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('suite_id', sa.INTEGER(), nullable=True),
    sa.Column('run_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('success_rate', sa.FLOAT(), nullable=False),
    sa.Column('hallucination_rate', sa.FLOAT(), nullable=False),
    sa.Column('tool_accuracy_rate', sa.FLOAT(), nullable=False),
    sa.Column('reliability_rate', sa.FLOAT(), nullable=False),
    sa.Column('avg_latency_ms', sa.FLOAT(), nullable=False),
    sa.Column('avg_cost_usd', sa.FLOAT(), nullable=False),
    sa.Column('case_count', sa.INTEGER(), nullable=False),
    sa.Column('pass_count', sa.INTEGER(), nullable=False),
    sa.Column('summary_json', sqlite.JSON(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['evaluation_suites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_suite_id'), 'evaluation_runs', ['suite_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_status'), 'evaluation_runs', ['status'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_started_at'), 'evaluation_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_run_id'), 'evaluation_runs', ['run_id'], unique=1)
    op.create_index(op.f('ix_evaluation_runs_name'), 'evaluation_runs', ['name'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_mode'), 'evaluation_runs', ['mode'], unique=False)
    op.create_table('evaluation_case_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('evaluation_run_id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('latency_ms', sa.FLOAT(), nullable=False),
    sa.Column('total_cost_usd', sa.FLOAT(), nullable=False),
    sa.Column('hallucination_score', sa.FLOAT(), nullable=False),
    sa.Column('tool_accuracy_score', sa.FLOAT(), nullable=False),
    sa.Column('reliability_score', sa.FLOAT(), nullable=False),
    sa.Column('assertion_results_json', sqlite.JSON(), nullable=False),
    sa.Column('output_json', sqlite.JSON(), nullable=False),
    sa.Column('trace_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_case_results_target_type'), 'evaluation_case_results', ['target_type'], unique=False)
    op.create_index(op.f('ix_evaluation_case_results_status'), 'evaluation_case_results', ['status'], unique=False)
    op.create_index(op.f('ix_evaluation_case_results_evaluation_run_id'), 'evaluation_case_results', ['evaluation_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_case_results_case_id'), 'evaluation_case_results', ['case_id'], unique=False)
    op.create_table('evaluation_suites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=32), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('config_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_suites_name'), 'evaluation_suites', ['name'], unique=1)
    op.create_index(op.f('ix_evaluation_suites_mode'), 'evaluation_suites', ['mode'], unique=False)
    op.create_index(op.f('ix_evaluation_suites_active'), 'evaluation_suites', ['active'], unique=False)
    # ### end Alembic commands ###
